//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation images.
        /// </summary>
        internal static string AccImgesTitle {
            get {
                return ResourceManager.GetString("AccImgesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation name.
        /// </summary>
        internal static string AccNameDataGrid {
            get {
                return ResourceManager.GetString("AccNameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation image:.
        /// </summary>
        internal static string AccommodationImage {
            get {
                return ResourceManager.GetString("AccommodationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation:.
        /// </summary>
        internal static string AccommodationLabel {
            get {
                return ResourceManager.GetString("AccommodationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation name:.
        /// </summary>
        internal static string AccommodationName {
            get {
                return ResourceManager.GetString("AccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add first comment:.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment:.
        /// </summary>
        internal static string AddCommnet {
            get {
                return ResourceManager.GetString("AddCommnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment on forum:.
        /// </summary>
        internal static string AddForumComment {
            get {
                return ResourceManager.GetString("AddForumComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add picture:.
        /// </summary>
        internal static string AddPicture {
            get {
                return ResourceManager.GetString("AddPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APATRMENT.
        /// </summary>
        internal static string ApartmentType {
            get {
                return ResourceManager.GetString("ApartmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival day.
        /// </summary>
        internal static string ArrivalDayDataGrid {
            get {
                return ResourceManager.GetString("ArrivalDayDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival day:.
        /// </summary>
        internal static string ArrivalDayDetails {
            get {
                return ResourceManager.GetString("ArrivalDayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus points:.
        /// </summary>
        internal static string BonusPoints {
            get {
                return ResourceManager.GetString("BonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book your accommodation!.
        /// </summary>
        internal static string BookAccTitle {
            get {
                return ResourceManager.GetString("BookAccTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK.
        /// </summary>
        internal static string BookButton {
            get {
                return ResourceManager.GetString("BookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation period.
        /// </summary>
        internal static string CancelationPeriodDataGrid {
            get {
                return ResourceManager.GetString("CancelationPeriodDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCLE.
        /// </summary>
        internal static string CancleButton {
            get {
                return ResourceManager.GetString("CancleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string CapacityDataGrid {
            get {
                return ResourceManager.GetString("CapacityDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change theme.
        /// </summary>
        internal static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in - check out:.
        /// </summary>
        internal static string ChcekInCheckOut {
            get {
                return ResourceManager.GetString("ChcekInCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose arrival day:.
        /// </summary>
        internal static string ChooseArrivalDay {
            get {
                return ResourceManager.GetString("ChooseArrivalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose departure day:.
        /// </summary>
        internal static string ChooseDepartureDay {
            get {
                return ResourceManager.GetString("ChooseDepartureDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string CityDataGrid {
            get {
                return ResourceManager.GetString("CityDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanliness.
        /// </summary>
        internal static string CleanlinessDataGrid {
            get {
                return ResourceManager.GetString("CleanlinessDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE FORUM.
        /// </summary>
        internal static string CloseForumButton {
            get {
                return ResourceManager.GetString("CloseForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string CommunicationDataGrid {
            get {
                return ResourceManager.GetString("CommunicationDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COTTAGE.
        /// </summary>
        internal static string CottageType {
            get {
                return ResourceManager.GetString("CottageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create forum.
        /// </summary>
        internal static string CreateForumTitle {
            get {
                return ResourceManager.GetString("CreateForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARK.
        /// </summary>
        internal static string darkTheme {
            get {
                return ResourceManager.GetString("darkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure day.
        /// </summary>
        internal static string DepartureDayDataGrid {
            get {
                return ResourceManager.GetString("DepartureDayDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure day:.
        /// </summary>
        internal static string DeparuteDayDetails {
            get {
                return ResourceManager.GetString("DeparuteDayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date:.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDateDataGrid {
            get {
                return ResourceManager.GetString("EndDateDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum comments.
        /// </summary>
        internal static string ForumCommentsTitle {
            get {
                return ResourceManager.GetString("ForumCommentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PDF.
        /// </summary>
        internal static string GeneratePDFButton {
            get {
                return ResourceManager.GetString("GeneratePDFButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to generate pdf reservation report?.
        /// </summary>
        internal static string GeneratePdfQuestion {
            get {
                return ResourceManager.GetString("GeneratePdfQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePage.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your next destination?.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOUSE.
        /// </summary>
        internal static string HouseType {
            get {
                return ResourceManager.GetString("HouseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageDataGrid {
            get {
                return ResourceManager.GetString("ImageDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateness.
        /// </summary>
        internal static string LatenessDataGrid {
            get {
                return ResourceManager.GetString("LatenessDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave comment.
        /// </summary>
        internal static string LeaveCommentButton {
            get {
                return ResourceManager.GetString("LeaveCommentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 1 - Nice to have.
        /// </summary>
        internal static string Level1NiceToHave {
            get {
                return ResourceManager.GetString("Level1NiceToHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2 - Minor complaints.
        /// </summary>
        internal static string Level2MinorComplaints {
            get {
                return ResourceManager.GetString("Level2MinorComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level3 - Really bothersome.
        /// </summary>
        internal static string Level3ReallyBothersome {
            get {
                return ResourceManager.GetString("Level3ReallyBothersome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level4 - Really necessary.
        /// </summary>
        internal static string Level4ReallyNecessary {
            get {
                return ResourceManager.GetString("Level4ReallyNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level5 - Very bad condition.
        /// </summary>
        internal static string Level5VeryBadCondition {
            get {
                return ResourceManager.GetString("Level5VeryBadCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        internal static string lightTheme {
            get {
                return ResourceManager.GetString("lightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfileTitle {
            get {
                return ResourceManager.GetString("MyProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reschadule requests.
        /// </summary>
        internal static string MyReschaduleRequestsTitle {
            get {
                return ResourceManager.GetString("MyReschaduleRequestsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  My reservations.
        /// </summary>
        internal static string MyReservationsTitle {
            get {
                return ResourceManager.GetString("MyReservationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reviews.
        /// </summary>
        internal static string MyReviewsTitle {
            get {
                return ResourceManager.GetString("MyReviewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameDataGrid {
            get {
                return ResourceManager.GetString("NameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of reservations:.
        /// </summary>
        internal static string NumberOfResevations {
            get {
                return ResourceManager.GetString("NumberOfResevations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of guests:.
        /// </summary>
        internal static string NumberOgGuests {
            get {
                return ResourceManager.GetString("NumberOgGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN FORUM.
        /// </summary>
        internal static string OpenForumButton {
            get {
                return ResourceManager.GetString("OpenForumButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner:.
        /// </summary>
        internal static string OwnerLabel {
            get {
                return ResourceManager.GetString("OwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s comment:.
        /// </summary>
        internal static string OwnersComment {
            get {
                return ResourceManager.GetString("OwnersComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string OwnerUsername {
            get {
                return ResourceManager.GetString("OwnerUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string OwnerUsernameDataGrid {
            get {
                return ResourceManager.GetString("OwnerUsernameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVOIUS.
        /// </summary>
        internal static string PreviousButton {
            get {
                return ResourceManager.GetString("PreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick search.
        /// </summary>
        internal static string QuickSearch {
            get {
                return ResourceManager.GetString("QuickSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere-Anytime.
        /// </summary>
        internal static string QuickSearchTitle {
            get {
                return ResourceManager.GetString("QuickSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Accommodation and Owner!.
        /// </summary>
        internal static string RateAccommodationAccAndOwnerTitle {
            get {
                return ResourceManager.GetString("RateAccommodationAccAndOwnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE.
        /// </summary>
        internal static string RateButton {
            get {
                return ResourceManager.GetString("RateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate cleanliness:.
        /// </summary>
        internal static string RateCleanliness {
            get {
                return ResourceManager.GetString("RateCleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate courtesy of the owner:.
        /// </summary>
        internal static string RateOwnerCourtesy {
            get {
                return ResourceManager.GetString("RateOwnerCourtesy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation for renovation.
        /// </summary>
        internal static string RecommodationTitle {
            get {
                return ResourceManager.GetString("RecommodationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add recommodaion for renorvation?.
        /// </summary>
        internal static string RenovationApproval {
            get {
                return ResourceManager.GetString("RenovationApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgency for renovation:.
        /// </summary>
        internal static string RenovationUrgency {
            get {
                return ResourceManager.GetString("RenovationUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area that needs renovation:.
        /// </summary>
        internal static string RenvationArea {
            get {
                return ResourceManager.GetString("RenvationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request details.
        /// </summary>
        internal static string RequestDetailsTitle {
            get {
                return ResourceManager.GetString("RequestDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESCHADULE.
        /// </summary>
        internal static string ReschaduleButton {
            get {
                return ResourceManager.GetString("ReschaduleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschadule reservation request.
        /// </summary>
        internal static string ReschduleResrvationTitle {
            get {
                return ResourceManager.GetString("ReschduleResrvationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string RescheduleRequests {
            get {
                return ResourceManager.GetString("RescheduleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved dates:.
        /// </summary>
        internal static string ReservationDays {
            get {
                return ResourceManager.GetString("ReservationDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation details.
        /// </summary>
        internal static string ReservationDetailsTitle {
            get {
                return ResourceManager.GetString("ReservationDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request dates:.
        /// </summary>
        internal static string ReservationRequestDates {
            get {
                return ResourceManager.GetString("ReservationRequestDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance reservation restrictions.
        /// </summary>
        internal static string ReservationRestricitonsDataGrid {
            get {
                return ResourceManager.GetString("ReservationRestricitonsDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESERVE.
        /// </summary>
        internal static string ReserveButton {
            get {
                return ResourceManager.GetString("ReserveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resrved by:.
        /// </summary>
        internal static string ResrevedBy {
            get {
                return ResourceManager.GetString("ResrevedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule following.
        /// </summary>
        internal static string RuleFollowingDataGrid {
            get {
                return ResourceManager.GetString("RuleFollowingDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND REQUEST.
        /// </summary>
        internal static string SendRequestButton {
            get {
                return ResourceManager.GetString("SendRequestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW ALL.
        /// </summary>
        internal static string ShowAllButton {
            get {
                return ResourceManager.GetString("ShowAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string ShowAllForumsTitle {
            get {
                return ResourceManager.GetString("ShowAllForumsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEE COMMENTS.
        /// </summary>
        internal static string ShowForumComments {
            get {
                return ResourceManager.GetString("ShowForumComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW IMAGES.
        /// </summary>
        internal static string ShowImagesButton {
            get {
                return ResourceManager.GetString("ShowImagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE DETAILS.
        /// </summary>
        internal static string ShowMoreDetailsButton {
            get {
                return ResourceManager.GetString("ShowMoreDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date:.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDateDataGrid {
            get {
                return ResourceManager.GetString("StartDateDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string StateDataGrid {
            get {
                return ResourceManager.GetString("StateDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request&apos;s status:.
        /// </summary>
        internal static string StatusRequest {
            get {
                return ResourceManager.GetString("StatusRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staying days:.
        /// </summary>
        internal static string StayingDays {
            get {
                return ResourceManager.GetString("StayingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMITT.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free dates suggestions.
        /// </summary>
        internal static string SuggestedDatesTitle {
            get {
                return ResourceManager.GetString("SuggestedDatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeDataGrid {
            get {
                return ResourceManager.GetString("TypeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very helpful.
        /// </summary>
        internal static string VeryHelpful {
            get {
                return ResourceManager.GetString("VeryHelpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your title:.
        /// </summary>
        internal static string YourTitle {
            get {
                return ResourceManager.GetString("YourTitle", resourceCulture);
            }
        }
    }
}
